language: python
python:
  - 3.4

before_install:
  - pip install -r requirements.txt


script:
  - coverage run --source=ingreso_pacientes manage.py test ingreso_pacientes
  - py.test

after_script:
  coveralls
